
on:
  workflow_call:
    inputs:
      config:
        type: string
        description: "The test configuration in json format."
        required: true
    secrets:
      RANCHER_TOKEN:
        description: "The rancher token to login to the rancher server."
      RANCHER_URL:
        description: "The rancher url to login to the rancher server."
jobs:
  get_test:
    name: "Parse test configuration"
    runs-on: ubuntu-latest
    outputs:
      id: ${{ steps.test.outputs.id }}
      name: ${{ steps.test.outputs.name }}
      clients: ${{ steps.test.outputs.clients }}
      kurtosis: ${{ steps.test.outputs.kurtosis }}
      worker: ${{ steps.test.outputs.worker }}
      backend: ${{ steps.test.outputs.backend }}
      pairs: ${{ steps.test.outputs.pairs }}
      assertoor_tests: ${{ steps.test.outputs.assertoor_tests }}
      kubernetes_cluster: ${{ steps.test.outputs.kubernetes_cluster }}
      kubernetes_storageclass: ${{ steps.test.outputs.kubernetes_storageclass }}
    steps:
    - name: "Parse test configuration"
      id: test
      shell: bash
      run: |
        testcfg=$(
        cat <<"EOF"
        ${{ inputs.config }}
        EOF
        )

        id="$(echo "$testcfg" | jq -r .id)"
        name="$(echo "$testcfg" | jq -r .name)"
        clients="$(echo "$testcfg" | jq -r .clients)"
        kurtosis="$(echo "$testcfg" | jq -r .kurtosis)"
        worker="$(echo "$testcfg" | jq -r .worker)"
        backend="$(echo "$testcfg" | jq -r .backend)"
        kubernetes_cluster="$(echo "$testcfg" | jq -r .kubernetes.cluster)"
        kubernetes_storageclass="$(echo "$testcfg" | jq -r .kubernetes.storageClass)"
        pairs="$(echo "$testcfg" | jq -c .clientPairs)"
        assertoor_tests="$(echo "$testcfg" | jq -c .assertoorTests)"

        echo "ID: $id"
        echo "id=$(echo "$id")" >> $GITHUB_OUTPUT
        echo "Name: $name"
        echo "name=$(echo "$name")" >> $GITHUB_OUTPUT
        echo "Clients yaml: $clients"
        echo "clients=$(echo "$clients")" >> $GITHUB_OUTPUT
        echo "Kurtosis yaml: $kurtosis"
        echo "kurtosis=$(echo "$kurtosis")" >> $GITHUB_OUTPUT
        echo "Worker: $worker"
        echo "worker=$(echo "$worker")" >> $GITHUB_OUTPUT
        echo "Backend: $backend"
        echo "backend=$(echo "$backend")" >> $GITHUB_OUTPUT
        if [ "$backend" == "kubernetes" ]; then
          echo "Kubernetes Cluster: $kubernetes_cluster"
          echo "kubernetes_cluster=$(echo "$kubernetes_cluster")" >> $GITHUB_OUTPUT
          echo "Kubernetes Storage Class: $kubernetes_storageclass"
          echo "kubernetes_storageclass=$(echo "$kubernetes_storageclass")" >> $GITHUB_OUTPUT
        else
          echo "kubernetes_cluster=" >> $GITHUB_OUTPUT
          echo "kubernetes_storageclass=" >> $GITHUB_OUTPUT
        fi
        echo "Client Pairs:"
        echo "$pairs" | yq -P
        echo "pairs=$(echo "$pairs" | jq -c 'to_entries | map({pairs:.value, index:.key})')" >> $GITHUB_OUTPUT
        echo "Assertoor Tests:"
        echo "$assertoor_tests" | yq -P
        echo "assertoor_tests=$(echo "$assertoor_tests")" >> $GITHUB_OUTPUT

  generate_kubeconfig:
    needs:
      - get_test
    name: "Generate kubeconfig"
    runs-on: ubuntu-latest
    if: ${{ needs.get_test.outputs.backend == 'kubernetes' }}
    steps:
    - name: "Install rancher CLI"
      shell: bash
      run: |
        curl -L https://github.com/rancher/cli/releases/download/v2.8.0/rancher-linux-amd64-v2.8.0.tar.gz | tar xvz
        mv ./rancher-v2.8.0/rancher /usr/local/bin/rancher
    - name: Login to rancher
      shell: bash
      run: |
        rancher login --token "${{ secrets.RANCHER_TOKEN }}" "${{ secrets.RANCHER_URL }}"
    - name: Login to kubernetes cluster
      shell: bash
      run: |
        rancher kubectl config use-context "${{ needs.get_test.outputs.kubernetes_cluster }}"
        rancher kubectl config 
    - name: Check kubernetes cluster
      shell: bash
      run: |
        set -e
        rancher kubectl get pods > /dev/null
    - name: Generate kubeconfig
      id: kubeconfig
      shell: bash
      run: |
        rancher kubectl config view --raw | base64 > kubeconfig
        echo "$KUBECONFIG" > kubeconfig
        echo "::set-output name=kubeconfig::$(cat kubeconfig)"

  run_with_docker:
    needs: get_test
    if: ${{ needs.get_test.outputs.backend == 'docker' }}
    strategy:
      fail-fast: false
      matrix:
        pair: ${{ fromJson(needs.get_test.outputs.pairs) }}
    name: "Run '${{ needs.get_test.outputs.name }}' in docker (#${{ matrix.pair.index }}: ${{ matrix.pair.pairs }})"
    uses: ./.github/workflows/_shared-run-docker.yaml
    with:
      id: "${{ needs.get_test.outputs.id }}_${{ matrix.pair.index }}"
      pairs: ${{ matrix.pair.pairs }}
      worker: ${{ needs.get_test.outputs.worker }}
      kurtosis: ${{ needs.get_test.outputs.kurtosis }}
      clients: ${{ needs.get_test.outputs.clients }}
      assertoor_tests: ${{ needs.get_test.outputs.assertoor_tests }}
  
  run_with_kubernetes:
    needs:
      - get_test
      - generate_kubeconfig
    if: ${{ needs.get_test.outputs.backend == 'kubernetes' }}
    strategy:
      fail-fast: false
      matrix:
        pair: ${{ fromJson(needs.get_test.outputs.pairs) }}
    name: "Run '${{ needs.get_test.outputs.name }}' in kubernetes (#${{ matrix.pair.index }}: ${{ matrix.pair.pairs }})"
    uses: ./.github/workflows/_shared-run-kubernetes.yaml
    with:
      id: "${{ needs.get_test.outputs.id }}_${{ matrix.pair.index }}"
      pairs: ${{ matrix.pair.pairs }}
      worker: ${{ needs.get_test.outputs.worker }}
      kurtosis: ${{ needs.get_test.outputs.kurtosis }}
      kubeCluster: ${{ needs.get_test.outputs.kubernetes_cluster }}
      kubeStorageClass: ${{ needs.get_test.outputs.kubernetes_storageclass }}
      clients: ${{ needs.get_test.outputs.clients }}
      assertoor_tests: ${{ needs.get_test.outputs.assertoor_tests }}
    secrets:
      KUBECONFIG: ${{ needs.generate_kubeconfig.outputs.kubeconfig }}


